// Generated by CoffeeScript 1.6.3
(function() {
  var convert;

  convert = require('./convert').convert;

  describe('Convert', function() {
    return it('will return one', function() {
      var result;
      result = convert(1);
      return expect(result).toBe("one");
    });
  });

}).call(this);
