// Generated by CoffeeScript 1.6.3
(function() {
  var convert, param, value;

  convert = require('./lib/convert').convert;

  param = process.argv[2];

  value = parseFloat(param.split('n=')[1]);

  console.log(convert(value));

}).call(this);
